on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - ci/*
name: environment test
jobs:
  live-job:
    environment: Live
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ vars.ENV_VAL }}" >> $GITHUB_STEP_SUMMARY
  dev:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ vars.ENV_VAL }}" >> $GITHUB_STEP_SUMMARY